### ISSUE TITLE
Memory leak for GRPC Binary

### ISSUE THREAD

**Issue by NicolasAlmerge** [google/grpc-binary#8]
I am using Firebase for an iOS app, running on XCode 15.0.1 with Swift 5.9.

I am using the latest version of Firebase (**10.17.0**), and when I debug memory leaks on my app, I see this:

```
1 instance of grpc_core::(anonymous namespace)::NativeClientChannelDNSResolver::Request leaked
```

We have a memory leak in the `grpc-core` library. It looks similar to [this issue](https://github.com/grpc/grpc/issues/31014) (although it might not be the same). I believe the problem is that this library is downloading `grpc` version **1.49.1** (as we can see [here](https://github.com/google/grpc-binary/blob/main/Package.swift#L57)). I think we should update the dependencies inside [`Package.swift`](https://github.com/google/grpc-binary/blob/main/Package.swift) to be able to fix this issue.

**Comment by paulb777** [comment]
Thanks for the report. It's not feasible for us to support Firestore working with any grpc minor version since adaptation is required for most grpc minor releases because it does not yet honor semantic versioning with Apple package managers. 

If you don't need to support iOS 12, using 10.15.0 could be a workaround.  (In 10.16.0, we backported Firebase to 1.49.1 to work around a gRPC crash on iOS 12.)

**Comment by NicolasAlmerge** [comment]
Thank you!

**Comment by ncooke3** [comment]
Closing. See https://github.com/firebase/firebase-ios-sdk/issues/12098#issuecomment-1992732149 for context
